bootstrap.memory_lock: false
cluster.name: elasticsearch
http.port: 9201
node.data: true
node.ingest: false
node.master: false
node.name: demo-node2
path.data: E:\bin\ELK\ElasticSearch\node2\Data
path.logs: E:\bin\ELK\ElasticSearch\node2\Logs
transport.tcp.port: 9301
xpack.license.self_generated.type: basic
xpack.security.enabled: false
discovery.zen.ping.unicast.hosts:
  - 127.0.0.1:9300

